import React from 'react';

const Content = () => {
    return <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In egestas tortor ut libero interdum porta. Maecenas viverra, arcu nec tempus pretium, mauris justo egestas lectus, eget porta turpis eros ut justo. Aenean ut mauris urna. Aliquam erat volutpat. Donec sagittis dolor non urna fermentum efficitur. Proin luctus lacus eu urna semper vulputate. Proin in aliquam metus. Suspendisse ut lacus erat. Nullam congue viverra mi, sed auctor est ornare vel. Nunc eget est feugiat, facilisis diam eu, feugiat metus. Vestibulum lacus diam, sollicitudin sit amet nulla non, dictum pellentesque nisi. Proin in lacus ac ligula viverra faucibus in eu sapien.

    Proin quam nisi, mattis vel purus ut, congue consectetur purus. Cras porttitor ex ut finibus mattis. Proin laoreet fringilla tortor, id tempor nunc dictum eget. Proin sit amet mattis lectus, sed semper sem. Pellentesque tristique sodales lacinia. Vivamus volutpat fermentum lorem, quis luctus eros posuere quis. Integer id ipsum elementum, dignissim est consectetur, venenatis mi.
    
    Etiam risus purus, mattis id fringilla sed, elementum sed sem. Ut accumsan et velit sit amet aliquet. Suspendisse rhoncus libero vel euismod placerat. Donec volutpat ante id mattis molestie. Nullam ut ante et nibh tempor eleifend. Proin posuere, magna quis pretium dapibus, justo augue rhoncus est, at posuere nisi erat tristique nibh. Curabitur eu arcu ornare, fringilla est vel, malesuada est. Maecenas rutrum enim urna, vitae laoreet turpis dapibus ut. Nulla vel placerat nisi. In ornare fringilla turpis at ultricies. Nulla fringilla fermentum lorem, sit amet tincidunt ligula. Fusce dolor mi, finibus nec sem vel, porttitor condimentum tellus. Praesent at dui ac lacus facilisis interdum. Nam pharetra dictum facilisis.
    
    Vestibulum porta quam ut sem ultricies, id convallis nibh placerat. Duis at tellus vitae augue sagittis ornare non eu urna. Nulla nec pretium tortor. Nullam commodo ex sit amet porttitor auctor. Proin porttitor dui a velit dignissim faucibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam ultrices fringilla dui, eu feugiat nibh tincidunt id. Phasellus aliquet lorem ac augue volutpat fringilla sit amet eget urna. Nulla vitae ante nec leo mattis bibendum. Vestibulum vulputate congue massa, vel efficitur lorem. Donec ac iaculis ante, posuere imperdiet nibh. Interdum et malesuada fames ac ante ipsum primis in faucibus. Integer non scelerisque libero. Vestibulum elementum posuere massa, eget imperdiet enim aliquet id. Etiam vehicula lectus id dui tristique blandit. Mauris mattis libero et quam luctus maximus.
    
    Duis ut semper neque, quis semper felis. Nulla lacus eros, egestas eget erat eu, auctor elementum nunc. In blandit elementum ex, vitae dignissim dui ultricies at. Morbi nec magna sed felis cursus lacinia. Vestibulum semper sit amet leo sed sodales. Vivamus id sapien at ligula ornare egestas. Mauris quis posuere nisl. Quisque eget dictum nibh. Mauris porta est non est dapibus finibus. Phasellus vulputate sollicitudin sapien vitae porta. Nulla facilisi. Praesent neque metus, molestie sed arcu et, viverra tristique dui. Morbi lacinia ex facilisis ultricies auctor.</p>;
}

export default Content;